theme: jekyll-theme-minimal
encoding: utf-8
future: true
title: Dispatches from Southeast Asia
description: 
baseurl: /sea
paginate: 4
paginate_path: "page:num"
plugins:
  - jekyll-paginate
  - jekyll-feed
